### ISSUE TITLE
Sessions not destroyed when using Filesystem handler

### ISSUE THREAD

**Issue by SharkyKZ** [joomla-framework/session#43]
Calling `FilesystemHandler::destroy()` with different session IDs seems to work correctly only the first time. It's why forcing logout in https://github.com/joomla/joomla-cms/pull/26891 didn't work.

**Comment by mbabker** [comment]
Are there any warnings or errors coming or is it just not working?  Because if I'm reading the C code right, as long as it's not going through `session_destroy()` you should be able to call a session handler's `destroy()` method multiple times, and `SessionHandler::destroy()` should either execute its internals or raise some kind of error (even `error_get_last()` should have something).

**Comment by SharkyKZ** [comment]
I don't see any errors. `SessionHandler::destroy()` always returns true. Session files are not deleted (except the first one).

**Comment by mbabker** [comment]
Well, short of debugging the C code inside `ext/session` for the `SessionHandler` class, or rewriting any of the handlers directly extending that to be custom implementations of `SessionHandlerInterface`, I don't really have an answer here.

**Comment by SharkyKZ** [comment]
>rewriting any of the handlers directly extending that to be custom implementations of SessionHandlerInterface

Is this an option? The example class from https://www.php.net/manual/en/class.sessionhandlerinterface seems to work.

**Comment by mbabker** [comment]
Yes it is an option but it would be good to understand why the inheritance from `SessionHandler` is a problem to know why it should be avoided (because this same issue is going to affect the WinCache handler too) instead of just doing a rewrite because "well this way seems to work better".

If you've found a legitimate bug in PHP, it should be reported upstream, and the code annotated with the bug being worked around (as the workaround could possibly go away when PHP support is raised beyond a version the fix was introduced in).  Without any warnings or anything like that to go off of, I would be more inclined to think you've either hit a bug in PHP or something that Joomla's trying to use in an unintended manner.

**Comment by SharkyKZ** [comment]
Filed a report https://bugs.php.net/bug.php?id=79587. Let's see where this goes.

**Comment by SharkyKZ** [comment]
Update: it's not a bug.
